### ISSUE TITLE
CocoaPods error while installation `ShadeView`

### ISSUE THREAD

**Issue by nteslyuk** [super-ultra/ShutterView#1]
I'm trying to install pod but every time I get the same error: "Unable to find a specification for `ShadeView`"

**Comment by super-ultra** [comment]
`ShadeView` is deprecated and will be deleted soon. Please use this pod https://github.com/super-ultra/UltraDrawerView.

**Comment by nteslyuk** [comment]
> `ShadeView` is deprecated and will be deleted soon. Please use this pod https://github.com/super-ultra/UltraDrawerView.

Thanks for quick answer
